CREATE DATABASE tools_DB;

USE DATABASE tools_DB;

CREATE TABLE (
    id INTEGER NOT NULL AUTO_INCREMENT,
    tool VARCHAR(255) NOT NULL,
    category VARCHAR(255) NOT NULL,
    descript VARCHAR(255),
    price DECIMAL(16, 2) NOT NULL,
    quantity INTEGER NOT NULL,
    lender VARCHAR(255) NOT NULL,
    PRIMARY KEY(id)
    )